POST http://locallhost:8080/api/v1/login
Content-Type: application/json

{
  "login": "admin",
  "password": "12345"
}

###
GET http://locallhost:8080/api/v1/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY5NDk2MTc2MSwicm9sZVNldCI6WyJCVVlFUiJdLCJmaXJzdE5hbWUiOiJzdHJpbmcifQ.n-5Z0wwrSbLenTno7wdQv-NVa6OqeFJaMLbR9VCddajLVAa_P_8LUm-QXteVRPfu9FGsHPvE7hwRbNBw3UTOgg

