http://locallhost:8080/api/v1/all
Authentication-Control: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY5NDk1MzcxNiwicm9sZVNldCI6WyJCVVlFUiJdLCJmaXJzdE5hbWUiOiJzdHJpbmcifQ.Hq2JSz8MD_9Dz_kcrlebEHbVJ5sd4MTYoXwETMyHO9iwxPAyql5dWRlSo4W0CwIOJbv8KNiMhJeSoCAU-AgI-Q