spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://java-mouse.ru/tickets
    username: user
    password: 69701
  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml
jwt:
  secret:
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==

